language: node_js
node_js:
- '4'
- '6'

branches:
  only:
  - master

before_script:
- npm install
- npm run build
script:
- ls js/
after_success:
- rm .travis.yml
- curl https://raw.githubusercontent.com/KamataRyo/travis-sctipts-collection/master/deploy-gh-pages.sh | bash

env:
  global:
  - NODE_VERSION_TO_DEPLOY: 6
  - GH_REF: github.com/KamataRyo/wacker-hands-on2
