language: node_js
node_js:
- '4'
- '6'

branches:
  only:
  - master

before_script:
- npm install
- npm run build

script:
- npm test

after_success:
- rm .gitignore
- rm .travis.yml
- curl https://raw.githubusercontent.com/KamataRyo/travis-sctipts-collection/master/deploy-gh-pages.sh | bash

env:
  global:
  - NODE_VERSION_TO_DEPLOY: 6
  - GH_REF: github.com/KamataRyo/wacker-hands-on
  - secure: "" #travis encryptコマンドで、Githubリポジトリへのアクセストークンを暗号化して指定する。README参照
