language: node_js
node_js:
- '4'
- '6'
branches:
  only:
  - master
before_script:
- npm install
- npm run build
script:
- npm test
after_success:
- rm .gitignore
- rm .travis.yml
- curl https://raw.githubusercontent.com/KamataRyo/travis-sctipts-collection/master/deploy-gh-pages.sh　| bash
env:
  global:
  - NODE_VERSION_TO_DEPLOY: 6
  - GH_REF: github.com/KamataRyo/wacker-hands-on
  - secure: "as9sBo86s15V7hIExhwk39fwTDsveZDGOqoeNa3e1gWAtWzst+JWtt5K0hV0PT3M9mLOVE5XOtHr83dhAZOMYD7o0VqvWg9QN2U8+B9eiBYlw4yiZWBDKhBTepETjk1GxWDm4iqZ1R49S6vwnwYfcFFEpVOiuKUkWfI4TcthQDMRmC7hoElBCSkjNc35gF/Ev7hJN8XzhjS5ryguVFBB5koVAOwcWqLhE8QAzCME6bYgQaOZXueKLhyuBa/QA7uruymaOIDjDPQUzpZ5aYdaSv8OlZdA4hZWZGMUQdK7Sr7OnqcmydmNtOGzDXDtbcjZ2SwS8XYBSmRTBKlPuRy0ZVTvxo015cX0hZM08Wts0wqM7CfvHdxZdSs2hheModEDiAdkafM4fDy04w+omdyzu+ByoF1PfxvPAQ6Ceqw46WoHY3eLxmaLNiPZgDUhm4cqUDqZ7Xl23hrOvcR4OH40a+HO7K42++RVeQfLQ6dPeg8M/VmuydVYA+RiXDnwAM7Y5ROodvKJJhpXZcvdMtgV/TjkcJI/l1/QV2Ek/Mh8BC1Uf7RnkABJCrLZAcevS1N/7wPjAV8SEpy7txjwcYBJoUZwMEBs7K5fpzSSpoX0igc/SGvPbV6Jo6PaYxNeqVSvifd6fjbewGUyzJRjqWhHY2AVWidiBmQWATQjfd7J5+k="
